### ISSUE TITLE
10hz logging

### ISSUE THREAD

**Issue by Stefal** [PaulZC/F9P_RAWX_Logger#1]
Hi!

Thank you for your sketch and the extensive documentation, it' a lot of work.

I've made some modifications on this [branch](https://github.com/Stefal/F9P_RAWX_Logger/tree/datetime_i2c):
- Use i2c to get date and time from the F9P
- Rewrite of the alarm calculation to support more than 60 minutes interval
- nmea output isn't needed anymore and I removed the GPS Adafruit dependencie
- Added a button to start a delayed stop

Do you want a pull request ?

My next goal is to log at [10Hz](https://github.com/Stefal/F9P_RAWX_Logger/tree/high_speed/Arduino) but I have some problems:
- some checksum errors
- Many errors reported when I convert the ubx file to rinex files.
- Sometimes the ringbuffer (24K) is full.

I don't know if my sketch is incorrect, or if I'm hardware limited on UART and if we should use I2c to get the data from the F9P.
Do you have an idea about this?

**Comment by PaulZC** [comment]
Hi Stefal,
Apologies - the code in this repo isn't as up to date as it should be. You can find the latest version in the [ZED-F9P_FeatherWing_USB repo](https://github.com/PaulZC/ZED-F9P_FeatherWing_USB). The I2C logger code uses the new multiSetVal functions for the F9 in the SparkFun u-blox library. Please check if [this version](https://github.com/PaulZC/ZED-F9P_FeatherWing_USB/blob/master/Arduino/RAWX_Logger_F9P_I2C/RAWX_Logger_F9P_I2C.ino) meets your needs.
My plan is to update the code in this repo as soon as I have time. I'll close this issue once I've done that. (I'm away from home at the moment.)
Best wishes,
Paul

**Comment by PaulZC** [comment]
Hi Stefal,
Thanks again for your comments.
I finally found time to update the RAWX_Logger_F9P_I2C code so it matches the code in the ZED-F9P_FeatherWing_USB repo.
I have also updated RAWX_Logger_F9P so it uses the SparkFun Ublox library and have removed the dependence on the Adafruit library.
I wouldn't recommend logging RAWX data to a single file for longer than 60 minutes. If you have a power glitch while logging, you could lose all your data. Joining the .ubx files together is easy to do so I'd recommend doing that if you can.
The delayed stop is a nice feature but I won't be adding it as I'd like to maintain compatibility with the [RAWX_Logger_Switches](https://github.com/PaulZC/RAWX_Logger_Switches).
I hope the I2C code fixes your 10Hz logging issues. Please let me know if it does.
All the best,
Paul

**Comment by Stefal** [comment]
Hi, and thank you for the update!
I'm still stuck at 8Hz. It looks like an arduino sd card bandwidth limit.

Sorry for answering so late, I'm a little busy on other projects, perhaps this one could interesting you: [RTKBase](https://github.com/Stefal/rtkbase)

**Comment by PaulZC** [comment]
Hi @Stefal ,
It may not be an SD card issue. It is probably because you have too many constellations enabled?
I have had RAWX running at 20Hz, but you can only do this using GPS only. If I have all constellations enabled, I2C starts to fail at about 5Hz. Sometimes you can go faster, but it depends how many SV's are in view and so how much RAWX data is being produced.
Good luck with your project! RTKBase looks nice! ;-) 
Best wishes,
Paul
