### ISSUE TITLE
Error in UBX.md

### ISSUE THREAD

**Issue by kikislater** [PaulZC/F9P_RAWX_Logger#2]
It's written : 

>   GPS.addCfgValset8(0x2091002a, 0x00);   // Change the last byte from 0x01 to 0x00 to leave NAV_POSLLH disabled
>   GPS.addCfgValset8(0x20910007, **0x01**);   // Change the last byte **from 0x01 to 0x00** to leave NAV_PVT disabled

But NAV_PVT is still 1, which configuration is correct ? 0 or 1 ?

**Comment by PaulZC** [comment]
Thank you Sylvain - I have [corrected the comment](https://github.com/PaulZC/F9P_RAWX_Logger/blob/master/Arduino/RAWX_Logger_F9P_I2C/RAWX_Logger_F9P_I2C.ino#L243-L244)

The NAV_PVT message is disabled by default.
If you want the NAV_PVT message to be enabled, the last byte should be 0x01.
If you want to leave the NAV_PVT message disabled, the last byte should be 0x00.

Best wishes,
Paul
