### ISSUE TITLE
SD Card Init Failed

### ISSUE THREAD

**Issue by uweboerst** [PaulZC/F9P_RAWX_Logger#4]
Hi Paul,
I followed your instructions to build a F9P_RAWX_Logger to the letter, but unfortunately I cannot get the adalogger to work properly. I always get the following error message in the serial plotter:

RAWX Logger F9P
Log GNSS RAWX data to SD Card
Green LED = Initial GNSS Fix
Red LED Flash = SD Write
Continuous Red indicates a problem or that logging has been stopped
Initializing GNSS...
Ublox GNSS found!
Rover mode selected
GNSS initialized!
Initializing SD card...
Panic!! SD Card Init Failed, or not present!
Waiting for reset...

I have built the logger twice (as I need a rover and a base station) and both have the same issue. I used different sd cards and formatted them properly but it didn't help.
Do you have any idea what could be the reason?
I would very much appreciate your support as my programing skills are very limited.

Uwe

**Comment by PaulZC** [comment]
Hi Uwe ( @uweboerst ),

What size SD card are you using - and have they been formatted with FAT32? Larger SD cards are formatted with ExFAT and the SdFat library does not currently support those. There are some instructions in [paragraph 4 here](https://github.com/PaulZC/F9P_RAWX_Logger/blob/master/HARDWARE.md#adafruit-feather-m0-adalogger).

If you want to test the Adalogger and card, Adafruit have some [examples](https://learn.adafruit.com/adafruit-feather-m0-adalogger/using-the-sd-card) to help you do that.

Please let me know if you need more help!

Best wishes,

Paul

**Comment by uweboerst** [comment]
Hi Paul,

thank you for your quick response.

I'm using a SDHC class 10 4GB SD card.

I tested the Adalogger and card with the examples provided by Arduino as suggested and they all work fine.

For example if I run CardInfo I get the following message:


> Initializing SD card...Wiring is correct and a card is present.
> 
> Card type:         SDHC
> Clusters:          122624
> Blocks x Cluster:  64
> Total Blocks:      7847936
> 
> Volume type is:    FAT32
> Volume size (Kb):  3923968
> Volume size (Mb):  3832
> Volume size (Gb):  3.74
> 
> Files found on the card (name, date and size in bytes):
> SYSTEM~1/     2020-10-06 23:33:12
>   INDEXE~1      2020-10-06 23:33:12 76


But I cannot run any of the examples that come with Bill Greiman's SdFat.

If I run bench§ (see code at the bottom of this post) provided by Greiman I do receive the following message:


> Use a freshly formatted SD for best performance.
> 
> Type any character to start
> chipSelect: 4
> FreeStack: 26804
> Can't access SD card. Do not reformat.
> SD errorCode: 0X50,0X0
> 

Is it possible that something is wrong with SdFat by Greiman? Do I have to change a pin or anything else?
Regards
Uwe



Code for bench§ by Bill Greiman:

`/*
 * This program is a simple binary write/read benchmark.
 */
#include <SPI.h>
#include "SdFat.h"
#include "sdios.h"
#include "FreeStack.h"

// Set USE_SDIO to zero for SPI card access. 
#define USE_SDIO 0

// SD chip select pin
const uint8_t chipSelect = 4;

// Size of read/write.
const size_t BUF_SIZE = 512;

// File size in MB where MB = 1,000,000 bytes.
const uint32_t FILE_SIZE_MB = 5;

// Write pass count.
const uint8_t WRITE_COUNT = 2;

// Read pass count.
const uint8_t READ_COUNT = 2;
//==============================================================================
// End of configuration constants.
//------------------------------------------------------------------------------
// File size in bytes.
const uint32_t FILE_SIZE = 1000000UL*FILE_SIZE_MB;

uint8_t buf[BUF_SIZE];

// file system
#if USE_SDIO
// Traditional DMA version.
// SdFatSdio sd;
// Faster version.
SdFatSdioEX sd;
#else  // USE_SDIO
SdFat sd;
#endif  // USE_SDIO

// Set ENABLE_EXTENDED_TRANSFER_CLASS to use extended SD I/O.
// Requires dedicated use of the SPI bus.
// SdFatEX sd;

// Set ENABLE_SOFTWARE_SPI_CLASS to use software SPI.
// Args are misoPin, mosiPin, sckPin.
// SdFatSoftSpi<6, 7, 5> sd;

// test file
SdFile file;

// Serial output stream
ArduinoOutStream cout(Serial);
//------------------------------------------------------------------------------
// Store error strings in flash to save RAM.
#define error(s) sd.errorHalt(F(s))
//------------------------------------------------------------------------------
void cidDmp() {
  cid_t cid;
  if (!sd.card()->readCID(&cid)) {
    error("readCID failed");
  }
  cout << F("\nManufacturer ID: ");
  cout << hex << int(cid.mid) << dec << endl;
  cout << F("OEM ID: ") << cid.oid[0] << cid.oid[1] << endl;
  cout << F("Product: ");
  for (uint8_t i = 0; i < 5; i++) {
    cout << cid.pnm[i];
  }
  cout << F("\nVersion: ");
  cout << int(cid.prv_n) << '.' << int(cid.prv_m) << endl;
  cout << F("Serial number: ") << hex << cid.psn << dec << endl;
  cout << F("Manufacturing date: ");
  cout << int(cid.mdt_month) << '/';
  cout << (2000 + cid.mdt_year_low + 10 * cid.mdt_year_high) << endl;
  cout << endl;
}
//------------------------------------------------------------------------------
void setup() {
  Serial.begin(9600);
  
  // Wait for USB Serial 
  while (!Serial) {
    SysCall::yield();
  }
  delay(1000);
  cout << F("\nUse a freshly formatted SD for best performance.\n");

  // use uppercase in hex and use 0X base prefix
  cout << uppercase << showbase << endl;
}
//------------------------------------------------------------------------------
void loop() {
  float s;
  uint32_t t;
  uint32_t maxLatency;
  uint32_t minLatency;
  uint32_t totalLatency;

  // Discard any input.
  do {
    delay(10);
  } while (Serial.available() && Serial.read() >= 0);

  // F( stores strings in flash to save RAM
  cout << F("Type any character to start\n");
  while (!Serial.available()) {
    SysCall::yield();
  }
  cout << F("chipSelect: ") << int(chipSelect) << endl;
  cout << F("FreeStack: ") << FreeStack() << endl;

#if USE_SDIO
  if (!sd.begin()) {
    sd.initErrorHalt();
  }
#else  // USE_SDIO  
  // Initialize at the highest speed supported by the board that is
  // not over 50 MHz. Try a lower speed if SPI errors occur.
  if (!sd.begin(chipSelect, SD_SCK_MHZ(50))) {
    sd.initErrorHalt();
  }
#endif  // USE_SDIO  
  cout << F("Type is FAT") << int(sd.vol()->fatType()) << endl;
  cout << F("Card size: ") << sd.card()->cardSize()*512E-9;
  cout << F(" GB (GB = 1E9 bytes)") << endl;

  cidDmp();

  // open or create file - truncate existing file.
  if (!file.open("bench.dat", O_RDWR | O_CREAT | O_TRUNC)) {
    error("open failed");
  }

  // fill buf with known data
  for (size_t i = 0; i < (BUF_SIZE-2); i++) {
    buf[i] = 'A' + (i % 26);
  }
  buf[BUF_SIZE-2] = '\r';
  buf[BUF_SIZE-1] = '\n';

  cout << F("File size ") << FILE_SIZE_MB << F(" MB\n");
  cout << F("Buffer size ") << BUF_SIZE << F(" bytes\n");
  cout << F("Starting write test, please wait.") << endl << endl;

  // do write test
  uint32_t n = FILE_SIZE/sizeof(buf);
  cout <<F("write speed and latency") << endl;
  cout << F("speed,max,min,avg") << endl;
  cout << F("KB/Sec,usec,usec,usec") << endl;
  for (uint8_t nTest = 0; nTest < WRITE_COUNT; nTest++) {
    file.truncate(0);
    maxLatency = 0;
    minLatency = 9999999;
    totalLatency = 0;
    t = millis();
    for (uint32_t i = 0; i < n; i++) {
      uint32_t m = micros();
      if (file.write(buf, sizeof(buf)) != sizeof(buf)) {
        sd.errorPrint("write failed");
        file.close();
        return;
      }
      m = micros() - m;
      if (maxLatency < m) {
        maxLatency = m;
      }
      if (minLatency > m) {
        minLatency = m;
      }
      totalLatency += m;
    }
    file.sync();
    t = millis() - t;
    s = file.fileSize();
    cout << s/t <<',' << maxLatency << ',' << minLatency;
    cout << ',' << totalLatency/n << endl;
  }
  cout << endl << F("Starting read test, please wait.") << endl;
  cout << endl <<F("read speed and latency") << endl;
  cout << F("speed,max,min,avg") << endl;
  cout << F("KB/Sec,usec,usec,usec") << endl;

  // do read test
  for (uint8_t nTest = 0; nTest < READ_COUNT; nTest++) {
    file.rewind();
    maxLatency = 0;
    minLatency = 9999999;
    totalLatency = 0;
    t = millis();
    for (uint32_t i = 0; i < n; i++) {
      buf[BUF_SIZE-1] = 0;
      uint32_t m = micros();
      int32_t nr = file.read(buf, sizeof(buf)); 
      if (nr != sizeof(buf)) {   
        sd.errorPrint("read failed");
        file.close();
        return;
      }
      m = micros() - m;
      if (maxLatency < m) {
        maxLatency = m;
      }
      if (minLatency > m) {
        minLatency = m;
      }
      totalLatency += m;
      if (buf[BUF_SIZE-1] != '\n') {
        error("data check");
      }
    }
    s = file.fileSize();
    t = millis() - t;
    cout << s/t <<',' << maxLatency << ',' << minLatency;
    cout << ',' << totalLatency/n << endl;
  }
  cout << endl << F("Done") << endl;
  file.close();
}`

**Comment by PaulZC** [comment]
Hi Uwe,

This is really very strange... I have lots of Adaloggers and I have never seen this issue before.

If both of your Adaloggers behave the same, it is unlikely to be a hardware fault.

I wonder if something has changed in one of the libraries or maybe the Adafruit SAMD board package? Maybe you could try using an earlier version of the Adafruit SAMD boards to being with. You can install this through the boards manager.

Let me know if you still have problems and I will try and replicate it here.

Best wishes,

Paul

**Comment by johnhulth** [comment]
Hi Paul, I was going to try your RAWX logger but i run into the same problem as Uwe. The Arduino Cardifo works fine, but i have problem with the SDfat library. I have tried both the original and Adafruits fork of SDfat with no luck. Did you find out what the problem might be?

/John

**Comment by johnhulth** [comment]
```
RAWX Logger F9P
Log GNSS RAWX data to SD card
Green LED = Initial GNSS Fix
Red LED Flash = SD Write
Continuous Red indicates a problem or that logging has been stopped
Initializing GNSS...
Panic!! Ublox GNSS not detected at default I2C address. Please check wiring. Freezing!
```
-------------------------------------------------------------
```
Initializing SD card...Wiring is correct and a card is present.

Card type:         SDHC
Clusters:          486880
Blocks x Cluster:  64
Total Blocks:      31160320

Volume type is:    FAT32
Volume size (Kb):  15580160
Volume size (Mb):  15215
Volume size (Gb):  14.86

Files found on the card (name, date and size in bytes): 
SYSTEM~1/     2021-01-14 11:44:48
  WPSETT~1.DAT  2021-01-14 11:44:48 12
  INDEXE~1      2021-01-14 11:44:52 76
DATALOG.TXT   2000-01-01 01:00:00 24492
TEST.TXT      2021-01-14 11:59:24 0
```

**Comment by johnhulth** [comment]
Doesn't work in RAWX logger 
```
RAWX Logger F9P
Log GNSS RAWX data to SD card
Green LED = Initial GNSS Fix
Red LED Flash = SD Write
Continuous Red indicates a problem or that logging has been stopped
Initializing GNSS...
Ublox GNSS found!
ROVER mode selected
GNSS initialized!
Initializing SD card...
Panic!! SD Card Init failed, or not present!
Waiting for reset...
```
...but it works fine with SD library and cardifo example.
```
Initializing SD card...Wiring is correct and a card is present.

Card type:         SDHC
Clusters:          486880
Blocks x Cluster:  64
Total Blocks:      31160320

Volume type is:    FAT32
Volume size (Kb):  15580160
Volume size (Mb):  15215
Volume size (Gb):  14.86

Files found on the card (name, date and size in bytes): 
SYSTEM~1/     2021-01-14 11:44:48
  WPSETT~1.DAT  2021-01-14 11:44:48 12
  INDEXE~1      2021-01-14 11:44:52 76
DATALOG.TXT   2000-01-01 01:00:00 24492
TEST.TXT      2021-01-14 11:59:24 0

```

**Comment by johnhulth** [comment]
Hi again, I found the problem.

https://github.com/PaulZC/F9P_RAWX_Logger/blob/fd0369ff45fa35357e6a470c0e77387afde262a0/Arduino/RAWX_Logger_F9P_I2C/RAWX_Logger_F9P_I2C.ino#L724

I had to lower the SPI speed to 12MHz
`if (!sd.begin(cardSelect, SD_SCK_MHZ(12))) {`
then it worked fine. Could be that i have a low quality SD-card. Obviously, it could not handle 50MHz.

```
RAWX Logger F9P
Log GNSS RAWX data to SD card
Green LED = Initial GNSS Fix
Red LED Flash = SD Write
Continuous Red indicates a problem or that logging has been stopped
Initializing GNSS...
Ublox GNSS found!
ROVER mode selected
GNSS initialized!
Initializing SD card...
SD Card initialized!
Waiting for GNSS fix...

Time: 14:20:34.0
Date: 14/1/2021
Fix: 3
Location: Lat: 59.658035 Lon: 10.631269 (degrees) Alt: 59.44 (m)
Ground Speed (m/s): 0.015
Heading: 0.0
Satellites: 29
PDOP: 1.08
Battery(V): 4.29
```

**Comment by PaulZC** [comment]
Great detective work @johnhulth - thank you for finding the problem!

@uweboerst : does John's solution work for you?

You might both be interested in the new version of the SparkFun u-blox GNSS library - it now has data logging functions built-in.
The new repo is [here](https://github.com/sparkfun/SparkFun_u-blox_GNSS_Arduino_Library) and the new data logging examples are [here](https://github.com/sparkfun/SparkFun_u-blox_GNSS_Arduino_Library/tree/master/examples/Data_Logging). The examples use the original Arduino SD library, which is quite slow. You will get better results with SdFat - please see [this issue](https://github.com/sparkfun/SparkFun_u-blox_GNSS_Arduino_Library/issues/1) for more details.

The new GNSS library has not yet been added to the Arduino Library Manager, but that will happen soon (probably in one or two days).

Best wishes,

Paul

**Comment by johnhulth** [comment]
Thanks Paul to point us to the new version of the u-blox library!

One thing I was wondering about, is there a reason why you power the F9P with 5V instead of with the 3.3V from the feather?

Also, I was running the RAWX logger with SPI speed 12Mhz, but already after a few minutes the feather hangs. Using the SDfat Adafruit fork and power from 3.3V. Haven't had time to investigate this, but any thoughts are welcome. Here is the last debug output: 
```
Sending: CLS:NAV ID:PVT Len: 0x0 Payload:
sendCommand: Waiting for No ACK response
checkUbloxI2C: OK, zero bytes available
checkUbloxI2C: OK, zero bytes available
checkUbloxI2C: OK, zero bytes available
checkUbloxI2C: OK, zero bytes available
checkUbloxI2C: OK, zero bytes available
checkUbloxI2C: OK, zero bytes available
checkUbloxI2C: OK, zero bytes available
checkUbloxI2C: OK, zero bytes available
checkUbloxI2C: OK, zero bytes available
checkUbloxI2C: OK, zero bytes available
checkUbloxI2C: Reading 100 bytes
Incoming: Size: 92 Received: CLS:NAV ID:PVT Len: 0x5C Payload: A8 2E B1 18 E5 7 1 E 13 4 7 37 18 0 0 0 28 D7 F8 FF 3 1 EA 19 53 34 56 6 37 18 8F 23 B4 E0 0 0 74 48 0 0 E7 3 0 0 58 6 0 0 9 0 0 0 EB FF FF FF DF FF FF FF 17 0 0 0 0 0 0 0 E4 0 0 0 80 A8 12 1 6E 0 0 0 6C 18 42 3E 0 0 0 0 0 0 0 0
packetCfg now valid
packetCfg classAndIDmatch
waitForNoACKResponse: valid data with CLS/ID match after 1017 msec
Location: Lat: 59.658043 Lon: 10.631278 (degrees) Alt: 57.52 (m)
Ground Speed (m/s): 0.023
Heading: 0.0
Satellites: 25
PDOP: 1.10
Battery(V): 4.31
getPVT: Polling

Sending: CLS:NAV ID:PVT Len: 0x0 Payload:
sendCommand: Waiting for No ACK response
checkUbloxI2C: OK, zero bytes available
checkUbloxI2C: OK, zero bytes available
checkUbloxI2C: OK, zero bytes available
checkUbloxI2C: OK, zero bytes available
checkUbloxI2C: OK, zero bytes available
checkUbloxI2C: OK, zero bytes available
checkUbloxI2C: OK, zero bytes available
checkUbloxI2C: OK, zero bytes available
checkUbloxI2C: OK, zero bytes available
checkUbloxI2C: OK, zero bytes available
checkUbloxI2C: Reading 100 bytes
Incoming: Size: 92 Received: CLS:NAV ID:PVT Len: 0x5C Payload: 90 32 B1 18 E5 7 1 E 13 4 8 37 18 0 0 0 F6 D5 F8 FF 3 1 EA 19 52 34 56 6 37 18 8F 23 D2 E0 0 0 92 48 0 0 E8 3 0 0 5B 6 0 0 0 0 0 0 FB FF FF FF F2 FF FF FF 5 0 0 0 0 0 0 0 EB 0 0 0 80 A8 12 1 6E 0 0 0 6C 18 42 3E 0 0 0 0 0 0 0 0
packetCfg now valid
packetCfg classAndIDmatch
waitForNoACKResponse: valid data with CLS/ID match after 1016 msec
getPVT: Polling

Sending: CLS:NAV ID:PVT Len: 0x0 Payload:
sendCommand: Waiting for No ACK response
checkUbloxI2C: OK, zero bytes available
checkUbloxI2C: OK, zero bytes available
checkUbloxI2C: OK, zero bytes available
checkUbloxI2C: OK, zero bytes available
checkUbloxI2C: OK, zero bytes available
checkUbloxI2C: OK, zero bytes available
checkUbloxI2C: OK, zero bytes available
checkUbloxI2C: OK, zero bytes available
checkUbloxI2C: OK, zero bytes available
checkUbloxI2C: Reading 100 bytes
Incoming: Size: 92 Received: CLS:NAV ID:PVT Len: 0x5C Payload: 78 36 B1 18 E5 7 1 E 13 4 9 37 18 0 0 0 C4 D4 F8 FF 3 1 EA 19 51 34 56 6 37 18 8F 23 F2 E0 0 0 B2 48 0 0 EA 3 0 0 5F 6 0 0 2 0 0 0 FF FF FF FF E0 FF FF FF 2 0 0 0 0 0 0 0 F4 0 0 0 80 A8 12 1 6E 0 0 0 6C 18 42 3E 0 0 0 0 0 0 0 0
packetCfg now valid
packetCfg classAndIDmatch
waitForNoACKResponse: valid data with CLS/ID match after 915 msec

Sending: CLS:CFG ID:0x8A Len: 0xA Payload: 0 1 0 0 1 0 21 30 FA 0
sendCommand: Waiting for ACK response
checkUbloxI2C: OK, zero bytes available
checkUbloxI2C: Reading 10 bytes
Incoming: Size: 2 Received: CLS:ACK ID:0x1 Len: 0x2 Payload: 6 8A
packetCfg now valid
packetAck now valid
packetCfg classAndIDmatch
packetAck classAndIDmatch
waitForACKResponse: no data and valid ACK after 102 msec

Sending: CLS:CFG ID:0x8A Len: 0x31 Payload: 0 1 0 0 A5 2 91 20 1 32 2 91 20 1 79 1 91 20 1 2A 0 91 20 0 7 0 91 20 1 1B 0 91 20 1 31 0 93 20 3 6 0 93 10 1 BB 0 91 20 1
sendCommand: Waiting for ACK response
checkUbloxI2C: OK, zero bytes available
checkUbloxI2C: Reading 10 bytes
Incoming: Size: 2 Received: CLS:ACK ID:0x1 Len: 0x2 Payload: 6 8A
packetCfg now valid
packetAck now valid
packetCfg classAndIDmatch
packetAck classAndIDmatch
waitForACKResponse: no data and valid ACK after 103 msec
Logging to 20210114/r_190409.ubx

```

**Comment by PaulZC** [comment]
The ZED draws quite a lot of current - over 100mA - so it is kinder to use 5V instead of asking the Adalogger regulator to provide all that current.
It also lets you power the system from the USB connector on the ZED breakout, if you want to.

**Comment by PaulZC** [comment]
Closing - because I think this issue is stale...
Please re-open if you need more advice.
Best wishes,
Paul
