### ISSUE TITLE
Restarting raw log

### ISSUE THREAD

**Issue by csomyy** [PaulZC/F9P_RAWX_Logger#7]
Hi Paul

Finally i could make this logger code work with ardufeather M0 board.
I'm using i2c code and 230400 baud with an Ardusimple F9P2B V3 board.
My issue is right now that logging restarts after a few minutes. Like 2-3. With the standard 15min rotation and 60min rotation setting too.
I had to reduce the sdcard frequency to 12mHz to work.
I tried to paste a pic ..

Do you have any suggestions where to look with this problem?

Earlier you mentioned a fresh code. Is there any other out of the box logging software for this M0 board?

![image](https://user-images.githubusercontent.com/85110866/128191363-1a634ba7-766c-4d05-8907-8329f21050d0.png)

**Comment by csomyy** [comment]
Ok, right now i found a case that log restarts if ubx_nmea_state == sync_lost.

Why is this necessary?

**Comment by PaulZC** [comment]
Hi @csomyy ,
It looks like you are trying to log RAWX data at 10Hz?
The code may not be able to keep up with that data rate.
Please try 5Hz and see what happens.
If the code loses sync (sync_lost) it will start looking for a new UBX packet starting with 0xB5. This will happen if data is lost or if there is a checksum error.
Best wishes,
Paul

**Comment by PaulZC** [comment]
Hi @csomyy ,

I am going to archive this repository. The logging code is out of date and has been superseded by the [SparkFun u-blox GNSS library data logging examples](https://github.com/sparkfun/SparkFun_u-blox_GNSS_Arduino_Library/tree/main/examples/Data_Logging).

Best wishes,
Paul
