### ISSUE TITLE
Switch to new SparkFun U-Blox librairy

### ISSUE THREAD

**Issue by Eric-FR** [PaulZC/F9P_RAWX_Logger#8]
The library used in the present code, [SparkFun_Ublox_Arduino_Library](https://github.com/sparkfun/SparkFun_Ublox_Arduino_Library) is deprecated.

SparkFun issued a new library: [SparkFun_u-blox_GNSS_Arduino_Library](https://github.com/sparkfun/SparkFun_u-blox_GNSS_Arduino_Library).

GPS has been replaced by GNSS in naming. Also, binary values for keys to configure and/or exchange with GNSS chips are now provided as const. This could simplify the RAWX_Logger code.

https://github.com/sparkfun/SparkFun_u-blox_GNSS_Arduino_Library#migrating-to-v20

**Comment by PaulZC** [comment]
Hi Eric,

Thank you for the nudge. I wrote this guide and the software long before I joined SparkFun... I had forgotten about it.

I am going to archive this repository. The logging code has been superseded by the [SparkFun u-blox GNSS library data logging examples](https://github.com/sparkfun/SparkFun_u-blox_GNSS_Arduino_Library/tree/main/examples/Data_Logging).

Best wishes,
Paul
